### ISSUE TITLE
phables test failed !

### ISSUE THREAD

**Issue by minhtrung1997** [Vini2/ds-bubbles#24]
**Describe the bug**
I have used micromamba to install phables, as I've finished my install, `phables install` work well, but `phables test` produces error message:
[phables_log_error.txt](https://github.com/Vini2/phables/files/12002108/phables_log_error.txt)

**Comment by minhtrung1997** [comment]
To fix the error, I have to install separately from the yaml file, following the command:
```
micromamba env create --quiet --file "/home/ktest/pipeline_env/software/environment/Trung_conda/phables-1.0.0/lib/python3.10/site-packages/phables/workflow/conda/4a5c5ed5b2e2312983716ca2e8acf6f5_.yaml" --prefix "/home/ktest/pipeline_env/software/environment/Trung_conda/phables-1.0.0/lib/python3.10/site-packages/phables/workflow/conda/4a5c5ed5b2e2312983716ca2e8acf6f5_"
```
And run the phables test smoothly !!!

**Comment by Vini2** [comment]
Hi @minhtrung1997,

Thanks for posting this issue. It looks like the latest release of mamba has some breaking changes. I will pin the mamba version and add a new release soon.

Thanks!

**Comment by Vini2** [comment]
Pinning `mamba<1.4.2`.

**Comment by Vini2** [comment]
Hello! I've added a new version of Phables to bioconda. I've pinned the version of mamba and now it should work fine.
