### ISSUE TITLE
File pattern of paired ends

### ISSUE THREAD

**Issue by shenwei356** [Vini2/ds-bubbles#32]
Hi, team, this is a little suggestion -- it's not very clear what the file names of PE reads should be.

I provided `s_1.fq.gz` and `s_2.fq.gz`, and it said no available PE files were found. I thought phables do not support .gz file, and also tried to rename fq to fastq, but still didn't have a clue. After checking the snakemake code, I finally realized that the file names should be `s_R1.fq.gz` and `s_R2.fq.gz` :smiling_face_with_tear: 

Maybe you could add some examples in the help message of the option or some other places, or you might also add support for different file patterns.

**Comment by Vini2** [comment]
Hi @shenwei356,

Thanks for posting this issue and I'm very sorry for the trouble. I will add an example to the help message and make it clear in the read the docs documentation.

**Comment by Vini2** [comment]
Hi @shenwei356,

Phables should now be able to handle the following file name patterns for paired-end reads.

```
*_R1_* and *_R2_*
*_R1.* and *_R2.*
*.R1.* and *.R2.*
*.R1_* and *.R2_*
*_1_* and *_2_*
*_1.* and *_2.*
*.1.* and *.2.*
*.1_* and *.2_*
```

I've updated the [documentation](https://phables.readthedocs.io/en/latest/assemble/) as well.

Closing the issue after fixing. Please reopen if needed.

Thanks!
