### ISSUE TITLE
Right GFA file to use?

### ISSUE THREAD

**Issue by GeoMicroSoares** [Vini2/ds-bubbles#34]
Hi there - I've assembled a metagenome with metaSPAdes and now want to use the resulting GFA with phables - my question is, what GFA is the correct GFA? Here's what I have from the assembly directory:
```
ll mgshot_S7938Nr1_metaspades3.15.5/*.gfa
mgshot_S7938Nr1_metaspades3.15.5/assembly_graph_after_simplification.gfa
mgshot_S7938Nr1_metaspades3.15.5/assembly_graph_with_scaffolds.gfa
mgshot_S7938Nr1_metaspades3.15.5/strain_graph.gfa
```

Thanks in advance!

**Comment by Vini2** [comment]
Hi @GeoMicroSoares,

Thanks for your interest in Phables.

You should use `assembly_graph_after_simplification.gfa` for metaSPAdes assemblies.

Thanks!

**Comment by GeoMicroSoares** [comment]
Hi there - thanks for this! Just to make sure - I'm running one GFA and providing the corresponding reads file. When `phables` starts, it actually finds all my samples based on the prefix (as shown in phables.samples.tsv). Is `phables` running the GFA against all reads files, or just listing them and only taking the reads files with prefixes matching the input GFA?

**Comment by Vini2** [comment]
Hi @GeoMicroSoares,

`phables` runs the GFA against all the read files present in the provided input directory assuming it is a cross assembly. If you want to run one GFA file against its corresponding reads files, then you should have those corresponding reads files in a separate directory and provide it as input. I hope this clarifies things. 

Thanks!

**Comment by Vini2** [comment]
Closing this issue after answering the question. Please reopen if needed.
