### ISSUE TITLE
Generating assembly graph

### ISSUE THREAD

**Issue by ellasiera** [Vini2/ds-bubbles#38]
Thank you for including recommendations for generating assembly graphs. However, since most of us don't generate that graph by default, and aren't fluent in assembly-graph-ing, it would be great to have some more detail.
For example, when using Megahit, there is a tool that gets the assembly graph from contigs of a certain kmer, but not of everything. Which graph should we use in this case?
Ideally you could add a feature that extracts an assembly graph in GFA given a contigs file and an assembler type, but I understand if that's beyond the scope of phables.

**Comment by Vini2** [comment]
Hi @ellasiera,

Thanks for your interest in Phables!

Of course, I will add some more details on generating assembly graphs for different assemblers in the Phables documentation.

I agree, adding a feature to generate the GFA file from the contigs file will be very useful. However, most popular tools do generate a GFA file and only a few assemblers don't. So at the moment, I'm not focused on adding any new features to Phables.

Thanks!

**Comment by Vini2** [comment]
Hi @ellasiera,

I've updated the [Phables assembly documentation](https://phables.readthedocs.io/en/latest/assemble/) with more details on processing assembly graphs. Please feel free to re-open this issue and let me know if you have any further questions.

Thanks!
