### ISSUE TITLE
[BUG] curl failed to verify the legitimacy of the server

### ISSUE THREAD

**Issue by pdec** [Vini2/ds-bubbles#43]
Hey,

during the fresh install of Phables it can not fetch PHROGs databases due to the SSL certificate problem of the site.

```bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

This might be solved by using `--insecure` in lines 43 and 69 when calling the `curl` in the install.smk 
https://github.com/Vini2/phables/blob/f83086dccb2fe40f907b830daa33508549174f63/phables/workflow/install.smk#L43
https://github.com/Vini2/phables/blob/f83086dccb2fe40f907b830daa33508549174f63/phables/workflow/install.smk#L69

**Comment by Vini2** [comment]
Hi @pdec,

Thanks for posting the issue! I'll fix the `curl` commands and make a new release.
