### ISSUE TITLE
koverage env in a conda strick channel priority

### ISSUE THREAD

**Issue by pdec** [Vini2/ds-bubbles#44]
Hey, 

I noticed that if you set `channel_priority strict` for conda the koverage env will not be solved unless you swap bioconda and conda-forge channels order

https://github.com/Vini2/phables/blob/8ae03300175404ff80c6d44c4e3aacb0dee0ef81/phables/workflow/envs/koverage.yaml#L3-L4

Cheers,
Przemek

**Comment by Vini2** [comment]
Hi @pdec,

Thanks for posting this issue. I will fix it.

**Comment by Vini2** [comment]
Fixed in commit [d4e4fa1](https://github.com/Vini2/phables/commit/d4e4fa13885f3f374fa41d75439ec7031f8fd127).
