### ISSUE TITLE
[Feature request] Handling mapping temporary files directory

### ISSUE THREAD

**Issue by pdec** [Vini2/ds-bubbles#45]
Hey,

the temporary/partial bam files are created in the directory where I run phables rather than in the output directory.
Do you think it is possible to enhance that? `*0001.bam`, `*0002.bam` etc.

Isn't that handled by the coverm's `--bam-file-cache-directory` flag? 

Cheers
Przemek

**Comment by Vini2** [comment]
Hi @pdec,

I think you can set the tmp directory for CoverM using the `TMPDIR` env variable. You can set it as follows.
```
TMPDIR=.
```
Got it from [https://github.com/wwood/CoverM/issues/41](https://github.com/wwood/CoverM/issues/41). Hope this helps.

Thanks,
Vijini

**Comment by Vini2** [comment]
Closing this issue. Please reopen if required.
