### ISSUE TITLE
Empty edges.fasta.frag.faa file despite correct input

### ISSUE THREAD

**Issue by jonye123** [Vini2/ds-bubbles#49]
Hi, I am running into an error with scan_smg because it says that my edges.fasta.frag.faa file is empty. I am not sure why this is the case as my input file is properly formatted as gfa.

**Comment by Vini2** [comment]
Hi @jonye123,

Thanks for your interest in Phables.

Can you please provide more details about the issue?
* What version of Phables are you using? You can get the version information using the command `phables --version`.
* What type of data are you running phables on? (metagenome, virome or phage isolate)
* Can you please share with me the log files `logs/smg_scan_frag_err.log` and `log/smg_scan_frag_out.log`? (you can drag and drop the files to the reply and they will attach).
* If possible, can you please share with me the GFA file you are using?

Thanks,
Vijini

**Comment by jonye123** [comment]
Hi Vijini,

Thanks for getting back to me so quickly! I am currently using version
1.3.1 and am running phables on a cyanophage genome I assembled using
SPAdes. I've attached the requested files to this email as well. The error
log (0 bytes) is empty so I am unable to attach it.

**Comment by jonye123** [comment]
Hi Vijini,

Thanks for getting back to me so quickly! I am currently using version 1.3.1 and am running phables on a cyanophage genome I assembled using SPAdes. I'm unable to attach the gfa file here, so I've emailed it.
[smg_scan_frag_out.log](https://github.com/Vini2/phables/files/14949702/smg_scan_frag_out.log)
[smg_scan_frag_err.log](https://github.com/Vini2/phables/files/14949703/smg_scan_frag_err.log)

**Comment by Vini2** [comment]
Hi @jonye123 

Can you please let me know the specs of the machine you are using to run Phables (OS, version, etc.)?

Thanks,
Vijini

**Comment by jonye123** [comment]
Yes, I am using macOS 13.6.1 (22G313). The processor is a 1.2 GHz Dual-Core
Intel Core m3. I currently have about 23 GB of storage available. Please
let me know if you need any more information,

Thanks,
Jon

**Comment by Vini2** [comment]
Hi @jonye123,

I believe macOS is the issue. Phables uses Fraggenescan to predict the genes in the sequences. I could not run Fraggenescan on macOS, only on Linux. I would suggest running Phables on a Linux machine.

I will make a note to replace Fraggenescan with probably Prodigal or pyrodigal.

Sorry about the inconvenience. Thanks for pointing out this issue.

Regards,
Vijini

**Comment by jonye123** [comment]
Thank you!

**Comment by jonye123** [comment]
Hi Vijini,

I tried running phables on a Linux virtual machine, however, I seem to
still be running into the same problem. Do you have any other thoughts as
to why this might be happening?

**Comment by Vini2** [comment]
Hi @jonye123,

That seems a bit strange. Can you please share with me your assembly graph file and edges file?

**Comment by jonye123** [comment]
Sure, no problem.

**Comment by Vini2** [comment]
Hi @jonye123,

Just checking if you sent me your assembly graph file and edges file.

Thanks!

**Comment by jonye123** [comment]
Hi,

Yes I sent them a few days ago! Were you able to receive them?

**Comment by Vini2** [comment]
Hi @jonye123,

No, I didn't get them. Did you email me?

**Comment by jonye123** [comment]
Yes, I replied in this thread. It said it was sent on the 18th

**Comment by Vini2** [comment]
Hi @jonye123,

Sorry, I haven't received the data. Can you upload it to Google Drive or DropBox and share it? Emailing might be a bit of an issue. 

Thanks!

**Comment by Vini2** [comment]
Hi @jonye123,

Sorry, it's been a while since you posted this issue. Was this issue fixed?

Can you please try the latest version of Phable (v1.3.3) and let me know if you still come across the error?

Thanks!

**Comment by jonye123** [comment]
Hi Vijini,

I ended taking a different direction with my project. Apologies for not
following up. I can take look at the updated version when I get the chance
though. Thanks!

**Comment by Vini2** [comment]
Closing the issue for now. Please re-open if needed.
