### ISSUE TITLE
marker.hmm file broken

### ISSUE THREAD

**Issue by nikolasbasler** [Vini2/ds-bubbles#53]
Hi,

I installed phables 1.3.2 via conda recently, following the instructions in the docs. `phables install` and `phables test` both finished successfully. However, the `marker.hmm` file, located in `mambaforge/envs/phables/lib/python3.11/site-packages/phables/workflow/../../databases/marker.hmm` only contains one line `404: Not Found`, causing phables runs on my data to crash. The `output/logs/smg_scan_hmm_err.log` reads:

`Error: File format problem in trying to open HMM file /vsc-hard-mounts/leuven-data/341/vsc34111/mambaforge/envs/phables/lib/python3.11/site-packages/phables/workflow/../../databases/marker.hmm.`
`Format tag is '404:': unrecognized.`
`Current H3 format is 'HMMER3/f'. Previous H2/H3 formats also supported.`

I deleted the `marker.hmm` file and re-ran `phables install`, but that just regenerates the file with the same content. 

Any help would be appreciated.

Thanks,
Nikolas

**Comment by Vini2** [comment]
Hi @nikolasbasler,

Thanks for your interest in Phables. 

The path to the `marker.hmm` file has been updated. I will fix it ASAP and put out a new release.

Thanks for bringing this to my attention.

**Comment by nikolasbasler** [comment]
Cool thanks! Will you also update the conda recipe?

**Comment by Vini2** [comment]
Hi @nikolasbasler,

The updated conda version is now live at [https://anaconda.org/bioconda/phables](https://anaconda.org/bioconda/phables). Please let me know if there are any further issues.

Thanks!

**Comment by Vini2** [comment]
Closing this issue after fixing it. Please re-open if needed.
