### ISSUE TITLE
"ERROR: Databases were not setup" and "ERROR: Snakemake failed" during phables installation through command prompt

### ISSUE THREAD

**Issue by JayWichanan** [Vini2/ds-bubbles#56]
**Describe the bug**
I'm trying to set up the Databases of Phables through "Phables install" but it turned out a couple errors
**To Reproduce**
Steps to reproduce the behaviour, including the
1. Activate the phables conda environment.
2. Run phables install.
2. ERROR: Databases were not setup and ERROR: Snakemake failed and some warning about Gurobi

**Expected behavior**
The tool should install without any errors.

**Screenshots**
(Phables) C:\WINDOWS\system32>phables install
[2024:07:31 06:41:41] Config file phables.out\config.yaml already exists. Using existing config file.
[2024:07:31 06:41:41] ------------------
[2024:07:31 06:41:41] | Runtime config |
[2024:07:31 06:41:41] ------------------

alpha: 1.2
compcount: 200
covtol: 100
databases: null
dir: C:\Users\Widku\miniconda3\envs\phables\Lib\site-packages\phables\test_data
evalue: 1E-10
input: null
log: phables/phables.log
longreads: false
maxpaths: 10
mgfrac: 0.2
mincov: 10
minlength: 2000
output: phables.out/
prefix: null
profile: null
resources:
  jobCPU: 8
  jobMem: 16000
seqidentity: 0.3

[2024:07:31 06:41:41] ---------------------
[2024:07:31 06:41:41] | Snakemake command |
[2024:07:31 06:41:41] ---------------------

snakemake -s C:\Users\Widku\miniconda3\envs\phables\Lib\site-packages\phables\workflow\install.smk --configfile phables.out\config.yaml --cores 1 --use-conda --conda-prefix C:\Users\Widku\miniconda3\envs\phables\Lib\site-packages\phables\workflow\conda --rerun-incomplete --printshellcmds --nolock --show-failed-logs
Restricted license - for non-production use only - expires 2025-11-24
C:\Users\Widku\miniconda3\envs\Phables\lib\site-packages\pulp\apis\gurobi_api.py:170: UserWarning: GUROBI error: Unknown parameter '_test'.
  warnings.warn("GUROBI error: {}.".format(e))
Config file C:\Users\Widku\miniconda3\envs\phables\Lib\site-packages\phables\workflow\..\config\config.yaml is extended by additional config specified via the command line.
Config file C:\Users\Widku\miniconda3\envs\phables\Lib\site-packages\phables\workflow\..\config\databases.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                       count
----------------------  -------
all                           1
phrog_annot_download          1
phrogs_mmseqs_download        1
smg_hmm_download              1
total                         4

Select jobs to execute...

[Wed Jul 31 06:41:51 2024]
rule phrogs_mmseqs_download:
    output: C:/Users/Widku/miniconda3/envs/phables/Lib/site-packages/phables/workflow/../../databases/phrogs_mmseqs_db
    jobid: 1
    reason: Missing output files: C:/Users/Widku/miniconda3/envs/phables/Lib/site-packages/phables/workflow/../../databases/phrogs_mmseqs_db
    resources: tmpdir=C:\Users\Widku\AppData\Local\Temp

            curl -Lko C:\Users\Widku\miniconda3\envs\phables\Lib\site-packages\phables\workflow\..\..\databases\phrogs_mmseqs_db.tar.gz https://phrogs.lmge.uca.fr/downloads_from_website/phrogs_mmseqs_db.tar.gz
            tar -xf C:\Users\Widku\miniconda3\envs\phables\Lib\site-packages\phables\workflow\..\..\databases\phrogs_mmseqs_db.tar.gz -C C:\Users\Widku\miniconda3\envs\phables\Lib\site-packages\phables\workflow\..\..\databases
            rm -rf C:\Users\Widku\miniconda3\envs\phables\Lib\site-packages\phables\workflow\..\..\databases\phrogs_mmseqs_db.tar.gz

Activating conda environment: ..\..\Users\Widku\miniconda3\envs\phables\Lib\site-packages\phables\workflow\conda\deb77479fe62a74e89d61de333668a55_
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 84.5M  100 84.5M    0     0  7434k      0  0:00:11  0:00:11 --:--:-- 8942k
Waiting at most 5 seconds for missing files.
MissingOutputException in rule phrogs_mmseqs_download in file C:\Users\Widku\miniconda3\envs\phables\Lib\site-packages\phables\workflow\install.smk, line 32:
Job 1  completed successfully, but some output files are missing. Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
C:/Users/Widku/miniconda3/envs/phables/Lib/site-packages/phables/workflow/../../databases/phrogs_mmseqs_db
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

ERROR: Databases were not setup.

Complete log: .snakemake\log\2024-07-31T064142.757802.snakemake.log
[2024:07:31 06:42:09] ERROR: Snakemake failed

**Desktop (please complete the following information):**
 - OS: [Window 10]
 - Browser [chrome]
 - Version [22H2]

**Additional context**

**Comment by Vini2** [comment]
Hi @JayWichanan,

I haven't tested Phables on a Windows machine and I believe some dependencies and commands used in Phables do not support Windows. 

If you have access, can you try on a Linux-based system?

**Comment by JayWichanan** [comment]
I have never used Linux before. Could you recommend the alternatives of Phables, which is more reliable than SPAdes and Unicycler. Just in case that I am not able to operate the Phables on Linux.

**Comment by JayWichanan** [comment]
I have already tried to install and run test, according to your instruction, on Linux-Ubuntu. Both Databases were set up and Snakemake also finished successfully. Thank you for your suggestion.
