### ISSUE TITLE
[BUG] Missing input exception in rule scan_smg

### ISSUE THREAD

**Issue by adijatj** [Vini2/ds-bubbles#58]
I tried running phable on my dataset, but the following error was encountered:

`snakemake -s /scratch/jmhadi001/.conda/envs/phables/lib/python3.9/site-packages/phables/workflow/phables.smk --configfile phables.out/config.yaml --cores 8 --use-conda --conda-prefix /scratch/jmhadi001/.conda/envs/phables/lib/python3.9/site-packages/phables/workflow/conda --rerun-incomplete --printshellcmds --nolock --show-failed-logs
Config file /scratch/jmhadi001/.conda/envs/phables/lib/python3.9/site-packages/phables/workflow/../config/config.yaml is extended by additional config specified via the command line.
Config file /scratch/jmhadi001/.conda/envs/phables/lib/python3.9/site-packages/phables/workflow/../config/databases.yaml is extended by additional config specified via the command line.
Output files will be saved to directory, phables.out

Building DAG of jobs...
MissingInputException in rule scan_smg in file /scratch/jmhadi001/.conda/envs/phables/lib/python3.9/site-packages/phables/workflow/rules/genes.smk, line 6:
Missing input files for rule scan_smg:
    output: phables.out/preprocess/edges.fasta.hmmout
    affected files:
        /scratch/jmhadi001/.conda/envs/phables/lib/python3.9/site-packages/phables/workflow/../../databases/marker.hmm`

[2024:08:04 01:07:09] ERROR: Snakemake failed

P.S. It worked just fine on the test files.

**Comment by Vini2** [comment]
Hi @adijatj,

Thanks for your interest in Phables. 

Can I know the version of Phables you are using? There was an issue with the old database download paths and it has been fixed in the latest version (1.4.0).

**Comment by Vini2** [comment]
Hi @adijatj,

Thanks for your interest in Phables. 

Have you already installed the databases using the command `phables install`?

Also, can I know the version of Phables you are using? You can use the command `phables --version` to get the installed version. There was an issue with the old database download paths and it has been fixed in the latest version (1.4.0).

**Comment by adijatj** [comment]
Thanks for your response. I use phables 1.4.0. 
Realized my database wasn't fully installed. Fixed now.
